name: Copy secrets to TAFL
on:
  workflow_dispatch:
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy ASC secrets to tafl repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CROSS_REPO }}
          ASC_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          ASC_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
          MATCH_PW: ${{ secrets.MATCH_PASSWORD }}
        run: |
          echo "$ASC_KEY_ID" | gh secret set APPSTORE_CONNECT_API_KEY_ID -R artemboev7-web/tafl
          echo "$ASC_ISSUER" | gh secret set APPSTORE_CONNECT_ISSUER_ID -R artemboev7-web/tafl
          echo "$ASC_KEY" | gh secret set APPSTORE_CONNECT_API_KEY -R artemboev7-web/tafl
          echo "$MATCH_PW" | gh secret set MATCH_PASSWORD -R artemboev7-web/tafl
          echo "Done!"
